name: Actualizacion Diaria Agro-Tech

on:
  schedule:
    - cron: '0 * * * *'  # EJECUTAR TODOS LOS DÍAS, A CADA HORA
  workflow_dispatch:     # Permite dar al botón "Run workflow" manualmente

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install -r requirements_monitors.txt

      - name: Ejecutar Monitores
        env:
          DATABASE_URL_NEON: ${{ secrets.DATABASE_URL_NEON }}
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
        run: |
          python clima_monitor.py
          python mercado_monitor.py
          python energia_monitor.py
          python monitor_agrotech.py
