name: AgroTech Pipeline Neon

on:
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install -r requirements_monitors.txt

      - name: Ejecutar Clima
        env:
          DATABASE_URL_NEON: ${{ secrets.DATABASE_URL_NEON }}
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
        run: python clima_monitor.py

      - name: Ejecutar Mercado
        env:
          DATABASE_URL_NEON: ${{ secrets.DATABASE_URL_NEON }}
        run: python mercado_monitor.py

      - name: Ejecutar Energia
        env:
          DATABASE_URL_NEON: ${{ secrets.DATABASE_URL_NEON }}
        run: python energia_monitor.py

      - name: Ejecutar Monitor Global
        env:
          DATABASE_URL_NEON: ${{ secrets.DATABASE_URL_NEON }}
        run: python monitor_agrotech.py
